# Generated by Django 5.2.8 on 2025-11-26 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Унікальний ключ, напр. MYPRJ', max_length=10, unique=True, verbose_name='Project Key (ID)')),
                ('name', models.CharField(max_length=255, verbose_name='Назва проєкту')),
                ('description', models.TextField(blank=True, verbose_name='Детальний опис')),
                ('status', models.CharField(choices=[('backlog', 'Backlog (В планах)'), ('in_progress', 'In Progress (В роботі)'), ('on_hold', 'On Hold (На паузі)'), ('completed', 'Completed (Завершено)'), ('archived', 'Archived (Архів)')], default='backlog', max_length=20, verbose_name='Статус')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20, verbose_name='Пріоритет')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата початку')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дедлайн (План)')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='Фактичне завершення')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_projects', to=settings.AUTH_USER_MODEL, verbose_name='Власник')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва етапу')),
                ('deadline', models.DateField(verbose_name='Дедлайн етапу')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершено')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва ресурсу')),
                ('resource_type', models.CharField(choices=[('url', 'URL Посилання'), ('file', 'Файл')], default='url', max_length=10)),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('file', models.FileField(blank=True, null=True, upload_to='project_resources/', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Project Owner (Manager)'), ('member', 'Member (Contributor)'), ('viewer', 'Viewer (Read Only)')], default='member', max_length=20, verbose_name='Роль у проєкті')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Учасник проєкту',
                'verbose_name_plural': 'Учасники проєкту',
                'unique_together': {('project', 'user')},
            },
        ),
    ]
