# Generated by Django 5.2.8 on 2026-03-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='is_active',
        ),
        migrations.AddField(
            model_name='sprint',
            name='actual_end_date',
            field=models.DateField(blank=True, help_text='Коли реально завершили спринт', null=True),
        ),
        migrations.AddField(
            model_name='sprint',
            name='status',
            field=models.CharField(choices=[('planned', 'Заплановано'), ('active', 'В роботі'), ('completed', 'Завершено')], default='planned', max_length=20),
        ),
    ]
