# Generated by Django 5.2.8 on 2026-07-15 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_sprint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500, verbose_name='Текст пункту')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Стан виконання')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='tasks.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskHistoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=50, verbose_name='Тип дії')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='Деталі змін')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Час події')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ініціатор зміни')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_events', to='tasks.task')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
