# Generated by Django 5.2.8 on 2026-07-16 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_taskchecklistitem_taskhistoryevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskresource',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tasks.taskcomment', verbose_name='Коментар'),
        ),
    ]
